### ISSUE TITLE
Display of functions with record patterns in parameters

### ISSUE THREAD

**Issue by Savelenko** [snuup/FSharp-File-Structure-for-Visual-Studio#1]
First of all, thank you for this extension! We have "waited" for this for years, it works quite well already! After installation and clicking through existing code base I ran into an issue with the following definition:

~~~
/// All product data in the given handling unit.
let productData { HandlingUnit.Products = ps } = ps |> List.map snd
~~~

The structure tree node for this function contains a "missing pattern" message.

**Comment by snuup** [comment]
Hi @Svalenko, I should have open sourced that some years ago ;)

As this was my private tool, I decided for a verbose messages that signal loudly when an expression is not handled. Now, as others use the tool it should be more polished and better silently omit expressions that are not primary targets for a file structure window.

Adapted the code accordingly and published new version 0.8 on VS marketplace. Please get the latest version and test.

**Comment by Savelenko** [comment]
Thanks for the swift fix, this seems to be resolved.

Do you mind/are you interested in more issue reports? There are some small cosmetic things I noticed. Nothing preventing normal use though.

**Comment by snuup** [comment]
Feel free to report issues you find. Its unlikely that I will fix them, but collecting them here makes certainly sense and maybe someone else touches the code. You can also jump in ;)

Please rate or review the extension at https://marketplace.visualstudio.com/items?itemName=snuup.FSharpFileStructure.
